### ISSUE TITLE
Chat room

### ISSUE THREAD

**Issue by srijonsaha** [ubclaunchpad/sync#51]

**Comment by cowmanjoe** [comment]
For the chat UI, how are we to differentiate the different clients if they don't name themselves? maybe an idea could be different colours? It could be good to also give them names similar to how google docs give names like "anonymous beaver" and "anonymous lizard" etc. This probably means the server will have to keep track of the client's (socket?) IDs and match them up to some data like name/colour.

**Comment by srijonsaha** [comment]
Yeah we need to name the users. The idea we had in mind was to once a user creates/joins a room the first thing they see is a modal to enter their name and once that's entered they get the actual room page. The name setting could be part of the implementing the chat feature.
