### ISSUE TITLE
Improve UX for inviting users to the room

### ISSUE THREAD

**Issue by cowmanjoe** [ubclaunchpad/sync#56]
From first use, I didn't know how to invite others to the room. I think we could add a UI element on the room page for copying the URL, or copying the code quickly (similar to GitHub's quick copying for cloning repos). This UI element could also have some text saying something like "send this link/code to your friends so they can join".

**Comment by johnagl** [comment]
Yup, I remember this was one of our todos, never around to doing it last term/writing a ticket for it.
