### ISSUE TITLE
Create some sort of module for shared code between frontend and backend

### ISSUE THREAD

**Issue by cowmanjoe** [ubclaunchpad/sync#67]
Since we have common event types between front end and back end, this code is duplicated. I am also creating more duplicate code because I am trying to send a typed object as an argument to a socket.io event. I feel like there may be more cases for shared code in the future for utility classes as well. 

Could maybe do this by creating an npm package as a library dependency for both front end and back end.

I think this is low priority because we don't have too much shared code yet and  this would probably cause more overhead than its worth. I thought I would write it down because I could see it being useful in the future, but we should probably hold off on it for a bit.

**Comment by srijonsaha** [comment]
I like this idea but I feel an npm package might be too much for the little bit of shared code we have. I wonder if there’s an easier way to share code.

**Comment by cowmanjoe** [comment]
Yeah I wouldn't be talking about putting one up in like an online repository or anything but just some way to do it locally. Would have to look into it more. Definitely possible that it would be not worth it.

**Comment by srijonsaha** [comment]
Having a separate module/directory outside of the backend one would cause issues with Heroku deployment as we only deploy the backend directory to Heroku as root. At the moment we only have the socket events strings that could be put in this shared directory. So not super worth it.
