### ISSUE TITLE
Video state should be given to new joiners of the room 

### ISSUE THREAD

**Issue by cowmanjoe** [ubclaunchpad/sync#70]
If the video is playing already and someone joins the room, it should start playing at the current time. Similarly, if it is paused, it should pause (maybe at the correct time as well). Currently the video stays in its "untouched" state where the YouTube logo is over the video.

**Comment by srijonsaha** [comment]
I think this is fairly similar to the queue feature and was thinking it would be done alongside the queue feature, you could add this as part of the queue feature or work on it after if you like.
